### ISSUE TITLE
Renderer Widget Classification and intervals are not not properly working

### ISSUE THREAD

**Issue by saurabhgis** [vojvod/CMV_Renderer_Widget#3]
@vojvod  have checked renderer widget in our application but its classification and intervals are not working property. by default it only working on Natural Breaks, my field is string and want to apply different methods and intervals(Equal Interval,Quantile,Standard Deviation,Geometrical Interval) and intervals(2,4,6,8) please suggest why its not working.

**Comment by vojvod** [comment]
Hi @saurabhgis please try to change your field from string to number (int, float or double).

**Comment by saurabhgis** [comment]
@vojvod  Thanks.
